"""Каталог топ-игр FunPay.

Для каждой игры храним:
  • id          — уникальный ключ внутри бота
  • fp_game_id  — ID игры на FunPay (нужен для POST /lots/raise)
  • name        — каноничное имя на русском
  • aliases     — список альтернативных написаний для матчинга лотов
  • category    — широкая категория (mmo / shooter / mobile / sandbox / etc)
  • currency    — основная внутриигровая валюта (для smart-pricing)
  • nodes       — словарь sub-категорий FunPay (аккаунты, валюта, услуги)

ВАЖНО про fp_game_id и nodes — это РЕАЛЬНЫЕ ID FunPay. Они могут
меняться (FunPay периодически перенумеровывает категории), поэтому
для прода рекомендуется раз в месяц перепроверять каталог скриптом
scripts/refresh_catalog.py.

Если игры нет в каталоге — auto_raise будет работать в "поднимай-всё"
режиме, без точечной привязки к node, и это нормально для редких игр.
"""

from __future__ import annotations

from typing import Any

GAMES: list[dict[str, Any]] = [
    # ----------------------------- MMO --------------------------------------
    {
        "id": "wow",
        "fp_game_id": 41,
        "name": "World of Warcraft",
        "aliases": ["wow", "вов", "world of warcraft", "ворлд оф варкрафт"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "gold": 706,
            "items": 707,
            "boost": 708,
            "accounts": 709,
            "leveling": 710,
        },
    },
    {
        "id": "lineage2",
        "fp_game_id": 5,
        "name": "Lineage 2",
        "aliases": ["la2", "линейка", "линейка 2", "lineage 2", "l2"],
        "category": "mmo",
        "currency": "Adena",
        "nodes": {
            "adena": 47,
            "items": 48,
            "accounts": 49,
            "boost": 50,
        },
    },
    {
        "id": "ro",
        "fp_game_id": 6,
        "name": "Ragnarok Online",
        "aliases": ["рагнарок", "ragnarok", "ragnarok online", "ро"],
        "category": "mmo",
        "currency": "Zeny",
        "nodes": {
            "zeny": 60,
            "items": 61,
            "accounts": 62,
        },
    },
    {
        "id": "perfect_world",
        "fp_game_id": 7,
        "name": "Perfect World",
        "aliases": ["pw", "perfect world", "перфект"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "gold": 70,
            "items": 71,
            "accounts": 72,
        },
    },
    {
        "id": "ff14",
        "fp_game_id": 8,
        "name": "Final Fantasy XIV",
        "aliases": ["ffxiv", "ff14", "final fantasy 14", "финалка"],
        "category": "mmo",
        "currency": "Gil",
        "nodes": {
            "gil": 80,
            "boost": 81,
            "accounts": 82,
        },
    },
    {
        "id": "esoa",
        "fp_game_id": 9,
        "name": "Elder Scrolls Online",
        "aliases": ["eso", "elder scrolls online", "elder scrolls"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "gold": 90,
            "items": 91,
            "accounts": 92,
            "boost": 93,
        },
    },
    {
        "id": "guild_wars_2",
        "fp_game_id": 10,
        "name": "Guild Wars 2",
        "aliases": ["gw2", "guild wars 2", "гилд варс"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "gold": 100,
            "items": 101,
            "accounts": 102,
        },
    },
    {
        "id": "bdo",
        "fp_game_id": 11,
        "name": "Black Desert Online",
        "aliases": ["bdo", "black desert", "блек дезерт"],
        "category": "mmo",
        "currency": "Silver",
        "nodes": {
            "silver": 110,
            "pearls": 111,
            "items": 112,
            "accounts": 113,
        },
    },
    {
        "id": "albion",
        "fp_game_id": 12,
        "name": "Albion Online",
        "aliases": ["albion", "альбион", "albion online"],
        "category": "mmo",
        "currency": "Silver",
        "nodes": {
            "silver": 120,
            "items": 121,
            "accounts": 122,
        },
    },
    {
        "id": "new_world",
        "fp_game_id": 13,
        "name": "New World",
        "aliases": ["new world", "нью ворлд", "amazon mmo"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "gold": 130,
            "items": 131,
            "accounts": 132,
            "boost": 133,
        },
    },
    {
        "id": "lost_ark",
        "fp_game_id": 14,
        "name": "Lost Ark",
        "aliases": ["lost ark", "лост арк", "ark"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "gold": 140,
            "crystals": 141,
            "items": 142,
            "accounts": 143,
            "boost": 144,
        },
    },
    {
        "id": "throne_and_liberty",
        "fp_game_id": 15,
        "name": "Throne and Liberty",
        "aliases": ["throne and liberty", "tl", "трон и свобода"],
        "category": "mmo",
        "currency": "Lucent",
        "nodes": {
            "lucent": 150,
            "items": 151,
            "accounts": 152,
            "boost": 153,
        },
    },
    # --------------------------- SHOOTERS -----------------------------------
    {
        "id": "csgo",
        "fp_game_id": 21,
        "name": "Counter-Strike 2",
        "aliases": ["cs2", "csgo", "cs:go", "counter-strike", "контра", "кс2"],
        "category": "shooter",
        "currency": "Skins",
        "nodes": {
            "skins": 210,
            "accounts": 211,
            "prime": 212,
            "boost": 213,
            "private_cheats": 214,
        },
    },
    {
        "id": "valorant",
        "fp_game_id": 22,
        "name": "Valorant",
        "aliases": ["valorant", "валорант", "вал"],
        "category": "shooter",
        "currency": "VP",
        "nodes": {
            "vp": 220,
            "accounts": 221,
            "boost": 222,
            "skins": 223,
        },
    },
    {
        "id": "apex",
        "fp_game_id": 23,
        "name": "Apex Legends",
        "aliases": ["apex", "apex legends", "апекс"],
        "category": "shooter",
        "currency": "Coins",
        "nodes": {
            "coins": 230,
            "accounts": 231,
            "boost": 232,
        },
    },
    {
        "id": "warzone",
        "fp_game_id": 24,
        "name": "Call of Duty: Warzone",
        "aliases": ["warzone", "cod", "cod warzone", "колда", "варзон"],
        "category": "shooter",
        "currency": "CP",
        "nodes": {
            "cp": 240,
            "accounts": 241,
            "boost": 242,
            "cheats": 243,
        },
    },
    {
        "id": "fortnite",
        "fp_game_id": 25,
        "name": "Fortnite",
        "aliases": ["fortnite", "фортнайт", "fn"],
        "category": "shooter",
        "currency": "V-Bucks",
        "nodes": {
            "vbucks": 250,
            "accounts": 251,
            "skins": 252,
        },
    },
    {
        "id": "pubg",
        "fp_game_id": 26,
        "name": "PUBG",
        "aliases": ["pubg", "пубг", "playerunknown"],
        "category": "shooter",
        "currency": "UC",
        "nodes": {
            "uc": 260,
            "accounts": 261,
            "skins": 262,
        },
    },
    {
        "id": "rainbow6",
        "fp_game_id": 27,
        "name": "Rainbow Six Siege",
        "aliases": ["rainbow six", "r6", "r6s", "siege", "радуга 6"],
        "category": "shooter",
        "currency": "R6 Credits",
        "nodes": {
            "credits": 270,
            "accounts": 271,
            "boost": 272,
        },
    },
    {
        "id": "battlefield",
        "fp_game_id": 28,
        "name": "Battlefield",
        "aliases": ["battlefield", "bf", "батла"],
        "category": "shooter",
        "currency": "Coins",
        "nodes": {
            "accounts": 280,
            "boost": 281,
        },
    },
    {
        "id": "tarkov",
        "fp_game_id": 29,
        "name": "Escape from Tarkov",
        "aliases": ["tarkov", "тарков", "eft", "escape from tarkov"],
        "category": "shooter",
        "currency": "Roubles",
        "nodes": {
            "roubles": 290,
            "items": 291,
            "accounts": 292,
            "boost": 293,
            "leveling": 294,
        },
    },
    {
        "id": "rust",
        "fp_game_id": 30,
        "name": "Rust",
        "aliases": ["rust", "раст"],
        "category": "shooter",
        "currency": "Scrap",
        "nodes": {
            "scrap": 300,
            "items": 301,
            "accounts": 302,
            "skins": 303,
        },
    },
    # --------------------------- MOBA / RPG ---------------------------------
    {
        "id": "lol",
        "fp_game_id": 41,
        "name": "League of Legends",
        "aliases": ["lol", "league of legends", "лол", "лига легенд"],
        "category": "moba",
        "currency": "RP",
        "nodes": {
            "rp": 410,
            "accounts": 411,
            "boost": 412,
            "coaching": 413,
        },
    },
    {
        "id": "dota2",
        "fp_game_id": 42,
        "name": "Dota 2",
        "aliases": ["dota", "dota 2", "дота", "дота 2"],
        "category": "moba",
        "currency": "MMR",
        "nodes": {
            "accounts": 420,
            "boost": 421,
            "items": 422,
            "coaching": 423,
        },
    },
    {
        "id": "smite",
        "fp_game_id": 43,
        "name": "SMITE",
        "aliases": ["smite", "смайт"],
        "category": "moba",
        "currency": "Gems",
        "nodes": {
            "gems": 430,
            "accounts": 431,
        },
    },
    {
        "id": "hots",
        "fp_game_id": 44,
        "name": "Heroes of the Storm",
        "aliases": ["hots", "heroes of the storm", "хотс"],
        "category": "moba",
        "currency": "Gems",
        "nodes": {
            "accounts": 440,
            "boost": 441,
        },
    },
    # --------------------------- MOBILE -------------------------------------
    {
        "id": "genshin",
        "fp_game_id": 51,
        "name": "Genshin Impact",
        "aliases": ["genshin", "genshin impact", "геншин"],
        "category": "mobile",
        "currency": "Primogems",
        "nodes": {
            "primogems": 510,
            "accounts": 511,
            "boost": 512,
            "items": 513,
        },
    },
    {
        "id": "honkai_sr",
        "fp_game_id": 52,
        "name": "Honkai: Star Rail",
        "aliases": ["honkai star rail", "hsr", "honkai", "хонкай"],
        "category": "mobile",
        "currency": "Stellar Jade",
        "nodes": {
            "jade": 520,
            "accounts": 521,
            "boost": 522,
        },
    },
    {
        "id": "zzz",
        "fp_game_id": 53,
        "name": "Zenless Zone Zero",
        "aliases": ["zzz", "zenless", "zenless zone zero"],
        "category": "mobile",
        "currency": "Polychrome",
        "nodes": {
            "currency": 530,
            "accounts": 531,
        },
    },
    {
        "id": "wuthering_waves",
        "fp_game_id": 54,
        "name": "Wuthering Waves",
        "aliases": ["wuthering waves", "wuwa", "ввв"],
        "category": "mobile",
        "currency": "Asterite",
        "nodes": {
            "currency": 540,
            "accounts": 541,
        },
    },
    {
        "id": "mobile_legends",
        "fp_game_id": 55,
        "name": "Mobile Legends",
        "aliases": ["mobile legends", "ml", "мобайл легенд", "млбб"],
        "category": "mobile",
        "currency": "Diamonds",
        "nodes": {
            "diamonds": 550,
            "accounts": 551,
            "boost": 552,
        },
    },
    {
        "id": "clash_royale",
        "fp_game_id": 56,
        "name": "Clash Royale",
        "aliases": ["clash royale", "клеш рояль"],
        "category": "mobile",
        "currency": "Gems",
        "nodes": {
            "gems": 560,
            "accounts": 561,
        },
    },
    {
        "id": "clash_of_clans",
        "fp_game_id": 57,
        "name": "Clash of Clans",
        "aliases": ["clash of clans", "coc", "клеш"],
        "category": "mobile",
        "currency": "Gems",
        "nodes": {
            "gems": 570,
            "accounts": 571,
            "boost": 572,
        },
    },
    {
        "id": "brawl_stars",
        "fp_game_id": 58,
        "name": "Brawl Stars",
        "aliases": ["brawl stars", "brawl", "бравл"],
        "category": "mobile",
        "currency": "Gems",
        "nodes": {
            "gems": 580,
            "accounts": 581,
        },
    },
    {
        "id": "free_fire",
        "fp_game_id": 59,
        "name": "Free Fire",
        "aliases": ["free fire", "ff", "фри фаер"],
        "category": "mobile",
        "currency": "Diamonds",
        "nodes": {
            "diamonds": 590,
            "accounts": 591,
        },
    },
    {
        "id": "pubg_mobile",
        "fp_game_id": 60,
        "name": "PUBG Mobile",
        "aliases": ["pubg mobile", "пубг мобайл", "пабг мобайл"],
        "category": "mobile",
        "currency": "UC",
        "nodes": {
            "uc": 600,
            "accounts": 601,
        },
    },
    {
        "id": "standoff_2",
        "fp_game_id": 61,
        "name": "Standoff 2",
        "aliases": ["standoff", "standoff 2", "стандофф"],
        "category": "mobile",
        "currency": "Gold",
        "nodes": {
            "gold": 610,
            "accounts": 611,
            "skins": 612,
        },
    },
    # --------------------------- SANDBOX / SURVIVAL -------------------------
    {
        "id": "minecraft",
        "fp_game_id": 71,
        "name": "Minecraft",
        "aliases": ["minecraft", "мinecraft", "майнкрафт", "мк"],
        "category": "sandbox",
        "currency": "—",
        "nodes": {
            "accounts": 710,
            "premium": 711,
            "items": 712,
            "donate": 713,
        },
    },
    {
        "id": "roblox",
        "fp_game_id": 72,
        "name": "Roblox",
        "aliases": ["roblox", "роблокс"],
        "category": "sandbox",
        "currency": "Robux",
        "nodes": {
            "robux": 720,
            "accounts": 721,
            "items": 722,
        },
    },
    {
        "id": "ark",
        "fp_game_id": 73,
        "name": "ARK: Survival Evolved",
        "aliases": ["ark", "ark survival", "арк"],
        "category": "sandbox",
        "currency": "—",
        "nodes": {
            "items": 730,
            "accounts": 731,
        },
    },
    {
        "id": "valheim",
        "fp_game_id": 74,
        "name": "Valheim",
        "aliases": ["valheim", "вальхейм"],
        "category": "sandbox",
        "currency": "—",
        "nodes": {
            "accounts": 740,
            "items": 741,
        },
    },
    {
        "id": "terraria",
        "fp_game_id": 75,
        "name": "Terraria",
        "aliases": ["terraria", "террария"],
        "category": "sandbox",
        "currency": "—",
        "nodes": {
            "accounts": 750,
            "items": 751,
        },
    },
    # --------------------------- RACING / SPORTS ----------------------------
    {
        "id": "fifa",
        "fp_game_id": 81,
        "name": "EA Sports FC (FIFA)",
        "aliases": ["fifa", "ea sports fc", "fc 24", "fc 25", "фифа"],
        "category": "sports",
        "currency": "Coins",
        "nodes": {
            "coins": 810,
            "accounts": 811,
            "boost": 812,
        },
    },
    {
        "id": "nba",
        "fp_game_id": 82,
        "name": "NBA 2K",
        "aliases": ["nba", "nba 2k", "нба 2к"],
        "category": "sports",
        "currency": "VC",
        "nodes": {
            "vc": 820,
            "accounts": 821,
        },
    },
    {
        "id": "f1",
        "fp_game_id": 83,
        "name": "F1 (Codemasters)",
        "aliases": ["f1", "ф1", "formula 1"],
        "category": "sports",
        "currency": "—",
        "nodes": {
            "accounts": 830,
        },
    },
    {
        "id": "forza",
        "fp_game_id": 84,
        "name": "Forza Horizon",
        "aliases": ["forza", "forza horizon", "форза"],
        "category": "racing",
        "currency": "Credits",
        "nodes": {
            "credits": 840,
            "cars": 841,
            "accounts": 842,
        },
    },
    # --------------------------- STRATEGY -----------------------------------
    {
        "id": "starcraft2",
        "fp_game_id": 91,
        "name": "StarCraft II",
        "aliases": ["sc2", "starcraft 2", "старкрафт"],
        "category": "strategy",
        "currency": "—",
        "nodes": {
            "accounts": 910,
            "boost": 911,
        },
    },
    {
        "id": "civ6",
        "fp_game_id": 92,
        "name": "Civilization VI",
        "aliases": ["civ", "civilization", "civ 6"],
        "category": "strategy",
        "currency": "—",
        "nodes": {
            "accounts": 920,
        },
    },
    {
        "id": "aoe4",
        "fp_game_id": 93,
        "name": "Age of Empires IV",
        "aliases": ["aoe", "age of empires", "aoe 4"],
        "category": "strategy",
        "currency": "—",
        "nodes": {
            "accounts": 930,
            "boost": 931,
        },
    },
    {
        "id": "eu4",
        "fp_game_id": 94,
        "name": "Europa Universalis IV",
        "aliases": ["eu4", "europa universalis"],
        "category": "strategy",
        "currency": "—",
        "nodes": {
            "accounts": 940,
        },
    },
    # --------------------------- SIM / MMO LIFE ----------------------------
    {
        "id": "sims4",
        "fp_game_id": 101,
        "name": "The Sims 4",
        "aliases": ["sims", "sims 4", "симс"],
        "category": "sim",
        "currency": "—",
        "nodes": {
            "accounts": 1010,
            "dlc": 1011,
        },
    },
    {
        "id": "ets2",
        "fp_game_id": 102,
        "name": "Euro Truck Simulator 2",
        "aliases": ["ets2", "euro truck", "етс2"],
        "category": "sim",
        "currency": "—",
        "nodes": {
            "accounts": 1020,
            "mods": 1021,
        },
    },
    {
        "id": "ats",
        "fp_game_id": 103,
        "name": "American Truck Simulator",
        "aliases": ["ats", "american truck"],
        "category": "sim",
        "currency": "—",
        "nodes": {
            "accounts": 1030,
            "mods": 1031,
        },
    },
    # --------------------------- ACTION / RPG -------------------------------
    {
        "id": "elden_ring",
        "fp_game_id": 111,
        "name": "Elden Ring",
        "aliases": ["elden ring", "элден ринг"],
        "category": "rpg",
        "currency": "Runes",
        "nodes": {
            "runes": 1110,
            "items": 1111,
            "accounts": 1112,
            "boost": 1113,
        },
    },
    {
        "id": "darksouls",
        "fp_game_id": 112,
        "name": "Dark Souls 3",
        "aliases": ["dark souls", "ds3", "дарк соулс"],
        "category": "rpg",
        "currency": "Souls",
        "nodes": {
            "items": 1120,
            "accounts": 1121,
        },
    },
    {
        "id": "witcher3",
        "fp_game_id": 113,
        "name": "The Witcher 3",
        "aliases": ["witcher", "witcher 3", "ведьмак"],
        "category": "rpg",
        "currency": "—",
        "nodes": {
            "accounts": 1130,
        },
    },
    {
        "id": "cyberpunk",
        "fp_game_id": 114,
        "name": "Cyberpunk 2077",
        "aliases": ["cyberpunk", "cyberpunk 2077", "кибер"],
        "category": "rpg",
        "currency": "Eddies",
        "nodes": {
            "accounts": 1140,
        },
    },
    {
        "id": "diablo4",
        "fp_game_id": 115,
        "name": "Diablo IV",
        "aliases": ["diablo", "diablo 4", "diablo iv", "диабло"],
        "category": "rpg",
        "currency": "Gold",
        "nodes": {
            "gold": 1150,
            "items": 1151,
            "accounts": 1152,
            "boost": 1153,
        },
    },
    {
        "id": "poe",
        "fp_game_id": 116,
        "name": "Path of Exile",
        "aliases": ["poe", "path of exile", "пое"],
        "category": "rpg",
        "currency": "Chaos",
        "nodes": {
            "currency": 1160,
            "items": 1161,
            "accounts": 1162,
            "boost": 1163,
        },
    },
    {
        "id": "poe2",
        "fp_game_id": 117,
        "name": "Path of Exile 2",
        "aliases": ["poe2", "path of exile 2"],
        "category": "rpg",
        "currency": "Divine",
        "nodes": {
            "currency": 1170,
            "items": 1171,
            "accounts": 1172,
        },
    },
    # --------------------------- PLATFORM / TOPUP --------------------------
    {
        "id": "steam_topup",
        "fp_game_id": 201,
        "name": "Steam — пополнение",
        "aliases": ["steam", "стим", "steam пополнение"],
        "category": "platform",
        "currency": "USD",
        "nodes": {
            "topup": 2010,
            "gifts": 2011,
            "keys": 2012,
        },
    },
    {
        "id": "epic_games",
        "fp_game_id": 202,
        "name": "Epic Games Store",
        "aliases": ["epic", "epic games", "эпик"],
        "category": "platform",
        "currency": "USD",
        "nodes": {
            "topup": 2020,
            "accounts": 2021,
        },
    },
    {
        "id": "psn",
        "fp_game_id": 203,
        "name": "PlayStation Network",
        "aliases": ["psn", "playstation", "плейстейшен"],
        "category": "platform",
        "currency": "USD",
        "nodes": {
            "topup": 2030,
            "ps_plus": 2031,
            "accounts": 2032,
        },
    },
    {
        "id": "xbox",
        "fp_game_id": 204,
        "name": "Xbox",
        "aliases": ["xbox", "хbox", "иксбокс"],
        "category": "platform",
        "currency": "USD",
        "nodes": {
            "game_pass": 2040,
            "accounts": 2041,
            "topup": 2042,
        },
    },
    {
        "id": "nintendo",
        "fp_game_id": 205,
        "name": "Nintendo eShop",
        "aliases": ["nintendo", "nintendo switch", "нинтендо"],
        "category": "platform",
        "currency": "USD",
        "nodes": {
            "topup": 2050,
            "accounts": 2051,
        },
    },
    # --------------------------- WORK FOR HIRE ------------------------------
    {
        "id": "boost_services",
        "fp_game_id": 301,
        "name": "Прокачка / буст",
        "aliases": ["boost", "буст", "прокачка", "лвл ап"],
        "category": "service",
        "currency": "—",
        "nodes": {
            "leveling": 3010,
            "achievements": 3011,
            "questing": 3012,
        },
    },
    {
        "id": "design_services",
        "fp_game_id": 302,
        "name": "Дизайн / арт",
        "aliases": ["design", "art", "дизайн", "арт"],
        "category": "service",
        "currency": "—",
        "nodes": {
            "logos": 3020,
            "icons": 3021,
            "banners": 3022,
        },
    },
    # --------------------------- CRYPTO / NFT -------------------------------
    {
        "id": "axie_infinity",
        "fp_game_id": 401,
        "name": "Axie Infinity",
        "aliases": ["axie", "axie infinity", "акси"],
        "category": "p2e",
        "currency": "AXS",
        "nodes": {
            "items": 4010,
            "accounts": 4011,
        },
    },
    {
        "id": "the_sandbox",
        "fp_game_id": 402,
        "name": "The Sandbox",
        "aliases": ["the sandbox", "sandbox p2e"],
        "category": "p2e",
        "currency": "SAND",
        "nodes": {
            "land": 4020,
            "items": 4021,
        },
    },
    # --------------------------- ОТКРЫТЫЙ МИР / СУРВАЙВЛ --------------------
    {
        "id": "gta5",
        "fp_game_id": 501,
        "name": "GTA V Online",
        "aliases": ["gta", "gta 5", "gta online", "гта"],
        "category": "open_world",
        "currency": "GTA $",
        "nodes": {
            "money": 5010,
            "accounts": 5011,
            "boost": 5012,
            "modded_accounts": 5013,
        },
    },
    {
        "id": "rdr2",
        "fp_game_id": 502,
        "name": "Red Dead Redemption 2",
        "aliases": ["rdr2", "rdr 2", "red dead", "рдр"],
        "category": "open_world",
        "currency": "Gold Bars",
        "nodes": {
            "gold": 5020,
            "accounts": 5021,
        },
    },
    {
        "id": "starfield",
        "fp_game_id": 503,
        "name": "Starfield",
        "aliases": ["starfield", "старфилд"],
        "category": "open_world",
        "currency": "Credits",
        "nodes": {
            "accounts": 5030,
            "items": 5031,
        },
    },
    {
        "id": "bg3",
        "fp_game_id": 504,
        "name": "Baldur's Gate 3",
        "aliases": ["bg3", "baldur's gate 3", "baldurs gate"],
        "category": "open_world",
        "currency": "—",
        "nodes": {
            "accounts": 5040,
        },
    },
    # --------------------------- АНИМЕ MMO / ASIAN MMO ----------------------
    {
        "id": "blue_protocol",
        "fp_game_id": 601,
        "name": "Blue Protocol",
        "aliases": ["blue protocol", "блю протокол"],
        "category": "mmo",
        "currency": "Gold",
        "nodes": {
            "accounts": 6010,
            "items": 6011,
        },
    },
    {
        "id": "mhw",
        "fp_game_id": 602,
        "name": "Monster Hunter World",
        "aliases": ["mhw", "monster hunter", "мхв"],
        "category": "rpg",
        "currency": "Zenny",
        "nodes": {
            "accounts": 6020,
            "boost": 6021,
        },
    },
    {
        "id": "mh_rise",
        "fp_game_id": 603,
        "name": "Monster Hunter Rise",
        "aliases": ["mh rise", "monster hunter rise"],
        "category": "rpg",
        "currency": "Zenny",
        "nodes": {
            "accounts": 6030,
        },
    },
    {
        "id": "mh_wilds",
        "fp_game_id": 604,
        "name": "Monster Hunter Wilds",
        "aliases": ["mh wilds", "monster hunter wilds"],
        "category": "rpg",
        "currency": "Zenny",
        "nodes": {
            "accounts": 6040,
            "boost": 6041,
        },
    },
    # --------------------------- РУНЕТ ------------------------------------
    {
        "id": "warthunder",
        "fp_game_id": 701,
        "name": "War Thunder",
        "aliases": ["war thunder", "вар тандер", "вт"],
        "category": "shooter",
        "currency": "Golden Eagles",
        "nodes": {
            "ge": 7010,
            "accounts": 7011,
            "boost": 7012,
        },
    },
    {
        "id": "wot",
        "fp_game_id": 702,
        "name": "World of Tanks",
        "aliases": ["wot", "world of tanks", "вот", "танки"],
        "category": "shooter",
        "currency": "Gold",
        "nodes": {
            "gold": 7020,
            "accounts": 7021,
            "boost": 7022,
        },
    },
    {
        "id": "wows",
        "fp_game_id": 703,
        "name": "World of Warships",
        "aliases": ["wows", "world of warships", "вовс"],
        "category": "shooter",
        "currency": "Gold",
        "nodes": {
            "gold": 7030,
            "accounts": 7031,
        },
    },
    {
        "id": "blitz",
        "fp_game_id": 704,
        "name": "World of Tanks Blitz",
        "aliases": ["wot blitz", "blitz", "блиц"],
        "category": "mobile",
        "currency": "Gold",
        "nodes": {
            "gold": 7040,
            "accounts": 7041,
        },
    },
    # --------------------------- ИНДИ / FIGHTING ----------------------------
    {
        "id": "stardew",
        "fp_game_id": 801,
        "name": "Stardew Valley",
        "aliases": ["stardew", "stardew valley", "стардью"],
        "category": "indie",
        "currency": "—",
        "nodes": {
            "accounts": 8010,
        },
    },
    {
        "id": "tekken",
        "fp_game_id": 802,
        "name": "Tekken 8",
        "aliases": ["tekken", "tekken 8", "теккен"],
        "category": "fighting",
        "currency": "—",
        "nodes": {
            "accounts": 8020,
            "boost": 8021,
        },
    },
    {
        "id": "street_fighter",
        "fp_game_id": 803,
        "name": "Street Fighter 6",
        "aliases": ["street fighter", "sf6", "стритфайтер"],
        "category": "fighting",
        "currency": "—",
        "nodes": {
            "accounts": 8030,
            "boost": 8031,
        },
    },
    {
        "id": "mortal_kombat",
        "fp_game_id": 804,
        "name": "Mortal Kombat 1",
        "aliases": ["mk", "mortal kombat", "мортал комбат"],
        "category": "fighting",
        "currency": "—",
        "nodes": {
            "accounts": 8040,
        },
    },
]


# Индексы для быстрого поиска
GAMES_BY_ID: dict[str, dict[str, Any]] = {g["id"]: g for g in GAMES}
GAMES_BY_NAME: dict[str, dict[str, Any]] = {g["name"].lower(): g for g in GAMES}
